#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "${PKGSRC_BRANCH}" in
    pkgsrc-2017Q2)  
      pkg ensure security/gnupg21
      ;;
    *)
      pkg ensure security/gnupg2
      ;;
  esac

  case "${DISTRIB_ID}" in
    Darwin)
      brew install pinentry-mac
      ;;
    Ubuntu)
      ${NOSUDO} sudo aptitude install -y libpcsclite1 pcscd pcsc-tools
      ;;
    Amazon)
      ${NOSUDO} sudo yum install -y gnupg2-smime
      ;;
  esac
}

bootstrap
