#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  pkg ensure security/gnupg21

  case "$(uname -s)" in
    Darwin)
      brew install pinentry-mac
      ;;
    *)
      ${NOSUDO} sudo aptitude install -y libpcsclite1 pcscd pcsc-tools
      ;;
  esac
}

bootstrap
