#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if ! type -P gpg2 >/dev/null; then
    return 1
  fi

  case "${DISTRIB_ID}" in
    Darwin)
      if [[ ! -x "$(type -P pinentry-mac)" ]]; then
        return 1
      fi
      ;;
  esac

  return 0
}

source sub "$BASH_SOURCE" "$@"
